### ISSUE TITLE
建议不要暴露自己的SMBIOS信息。

### ISSUE THREAD

**Issue by whidy** [ljhang/Ryzen-5800x-ASUS-PRIME-X570-PRO-OC-0.7.8#1]
有幸我的原仓对你有帮助，我也是因为OTA到Monterey失败了，又调试半天opencore都没法再启动了，找解决方案，恰好搜到你这个仓库。

既然你的Monterey能成功，我想大概还是我之前的opencore哪里不对劲。

然后顺便仔细看了下你的这个EFI，发现你的SMBIOS信息保留了，这个建议不要暴露，或者真实PC跟这个不一样，否则可能存在问题。

另外很好奇有线网络是正常的吗，我看文档说有线不支持，还没测试。

在另外你有用无线吗，似乎你的kext有点多和乱- -~

**Comment by ljhang** [comment]
> 有幸我的原仓对你有帮助，我也是因为OTA到Monterey失败了，又调试半天opencore都没法再启动了，找解决方案，恰好搜到你这个仓库。
> 
> 既然你的Monterey能成功，我想大概还是我之前的opencore哪里不对劲。
> 
> 然后顺便仔细看了下你的这个EFI，发现你的SMBIOS信息保留了，这个建议不要暴露，或者真实PC跟这个不一样，否则可能存在问题。
> 
> 另外很好奇有线网络是正常的吗，我看文档说有线不支持，还没测试。
> 
> 在另外你有用无线吗，似乎你的kext有点多和乱- -~

**Comment by ljhang** [comment]
@whidy 感谢。
我猜是OC版本不一致或者什么吧。
现在这个Kext的有线网络是正常使用，之前我看最新版的修复了Intel(R) i211无法连接问题了。主板没带Wi-Fi的，没有用无线，也懒得买无线网卡了咯。
